db:
  type: "mysql"
  user: "user"
  password: "1111"
  protocol: "tcp"
  address: "ledger-db:3306"
  schema: "household_ledger"
  params: "multiStatements=true"

server:
  host: "http://127.0.0.1"
  port: "8080"
