version: "3.8"
services:
  mysql:
    image: mysql:5.7
    container_name: ledger-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_SCHEMA}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - .volumes/mysql:/var/lib/mysql
    ports:
      - 3306:3306