FROM golang:1.19-alpine AS build
RUN apk update && apk add git

RUN mkdir -p /ledger
WORKDIR /ledger

COPY .. .
RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o financial-ledger main.go

FROM scratch

COPY --from=build /ledger/financial-ledger .
COPY --from=build /ledger/cfg/prd.yaml ./cfg/

ENV CONFIG_PROFILE=prd
EXPOSE 8080

CMD ["./financial-ledger"]