definitions:
  resource.ReqAddLedger:
    properties:
      date:
        type: string
      description:
        type: string
      income:
        type: integer
      user_id:
        type: string
    required:
    - date
    - description
    - income
    - user_id
    type: object
  resource.ReqSignIn:
    properties:
      email:
        type: string
      password:
        maxLength: 18
        minLength: 8
        type: string
    required:
    - password
    type: object
  resource.ReqSignUp:
    properties:
      email:
        type: string
      password:
        maxLength: 18
        minLength: 8
        type: string
    required:
    - password
    type: object
  resource.ResAddLedger:
    properties:
      ledger_id:
        type: integer
      user_id:
        type: string
    type: object
  resource.ResErr:
    properties:
      error:
        type: string
    type: object
  resource.ResGetLedger:
    properties:
      date:
        type: string
      description:
        type: string
      income:
        type: integer
      ledger_id:
        type: string
      user_id:
        type: string
    type: object
  resource.ResGetLedgers:
    properties:
      ledgers:
        items:
          $ref: '#/definitions/resource.ResGetLedger'
        type: array
    type: object
  resource.ResGetTime:
    properties:
      date:
        type: string
      timestamp:
        type: string
    type: object
  resource.ResSignIn:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  resource.ResSignUp:
    properties:
      user_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/household-ledger/ledger:
    post:
      consumes:
      - application/json
      description: Adds ledger to db.
      parameters:
      - description: Add ledger request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/resource.ReqAddLedger'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/resource.ResAddLedger'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/resource.ResErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/resource.ResErr'
      summary: Add ledger
      tags:
      - Ledger
  /api/household-ledger/ledger/{ledger_id}:
    get:
      description: Gets ledger with {ledger_id} from db.
      parameters:
      - description: ledger id
        in: path
        name: ledger_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resource.ResGetLedger'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/resource.ResErr'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/resource.ResErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/resource.ResErr'
      summary: Get ledger
      tags:
      - Ledger
  /api/household-ledger/ledgers/{user_id}:
    get:
      description: Gets ledgers with {user_id} from db.
      parameters:
      - description: user id
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resource.ResGetLedgers'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/resource.ResErr'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/resource.ResErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/resource.ResErr'
      summary: Get ledgers
      tags:
      - Ledger
  /api/household-ledger/ping:
    get:
      description: Ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/resource.ResErr'
      summary: Ping
      tags:
      - Basic
  /api/household-ledger/time:
    get:
      description: Time
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resource.ResGetTime'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/resource.ResErr'
      summary: Time
      tags:
      - Basic
  /api/household-ledger/user/signin:
    post:
      consumes:
      - application/json
      description: Signs user in.
      parameters:
      - description: Sign in request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/resource.ReqSignIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resource.ResSignIn'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/resource.ResErr'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/resource.ResErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/resource.ResErr'
      summary: Sign in
      tags:
      - User
  /api/household-ledger/user/signup:
    post:
      consumes:
      - application/json
      description: Signs user up.
      parameters:
      - description: Sign up request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/resource.ReqSignUp'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/resource.ResSignUp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/resource.ResErr'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/resource.ResErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/resource.ResErr'
      summary: Sign up
      tags:
      - User
swagger: "2.0"
